#!/usr/bin/env bash

BASECMD="$HOME/LGWebOSRemote/venv/bin/lgtv TV"

case "$1" in
  "up")
  $BASECMD volumeUp 2>/dev/null
  ;;
  "down")
  $BASECMD volumeDown 2>/dev/null
  ;;
  "")
  echo "No volume specified, and GETting isn't supported yet :("
  ;;
  "*")
  $BASECMD setVolume $1 2>/dev/null
  ;;
esac

if [ -z "$1" ]; then
    exit 0
else
    $BASECMD openYoutubeURL "$1" 2>/dev/null
fi
